name: kobpay_mobile
description: KOBPAY Flutter client
publish_to: "none"

version: 0.1.1+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  file_picker: ^8.0.7
  http_parser: ^4.0.2
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/banners/
    - assets/icon/
    - assets/splash/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icon/icon.png
